### ISSUE TITLE
Be more verbose and blocking on deployment

### ISSUE THREAD

**Issue by fj** [cloud66-oss/cx#28]
When a stack is redeployed, `cx` should report what was deployed to, what ref was deployed, and the deployment id and URL that results from doing so. Otherwise the only way to confirm that the correct thing was deployed is to check the GUI manually.

I think this should also happen optionally in a blocking way, so that other workflow commands can chain with `cx redeploy` rather than needing to poll for status.

**Comment by khash** [comment]
That's a great suggestion. There is a the `listen` command (http://help.cloud66.com/toolbelt/toolbelt-listen-command) which will give more info but probably is not going to work in your chain scenario.

Can you tell me a bit about the syntax you envisage that's going to work about the workflow?

**Comment by fj** [comment]
The preferred approach would be to make the _default_ invocation of `cx redeploy` be blocking, so no new syntax would be required for that case, and you just add a flag to make it not blocking. I'm imagining output like:

```
cx redeploy -s globocorp-web-staging --git-ref topic/beta-design
-- Beginning redeploy:
  * source: (git repository)
     * remote: git://github.com/globocorp/website.git
     * ref: topic/beta-design
  * stack: globocorp-web-staging
-- Pushing 149/149 (100%) KiB... done
-- Reticulating splines... done
-- [ more details ]
-- Updating deploy directory... done

Deployment completed to globocorp-web-staging
```

Preferably all this will happen with nice colors to make things visible or highlight problems. The nonblocking version would be, say:

```
cx redeploy --async -s globocorp-web-staging --git-ref topic/beta-design
-- Beginning redeploy:
  * source: (git repository)
     * remote: git://github.com/globocorp/website.git
     * ref: topic/beta-design
  * stack: globocorp-web-staging

Check <your C66 stack url> for progress.
```

**Comment by khash** [comment]
Thanks for the clarification. Apart from the additional explicit information on git refs, I think you can use the `listen` flag on redeploy which makes it blocking. It is the opposite of your suggested behaviour but since `listen` is a new flag we didn't want to change the API for the command line as we have users with scripts written against `cx` given it's default behaviour.

Does this help?

**Comment by fj** [comment]
> Apart from the additional explicit information on git refs, I think you can use the listen flag on redeploy which makes it blocking.

I don't think that's true. `listen` doesn't wait for you to listen; there is a race condition that occurs between when `redeploy` finishes and `listen` begins, so `cx redeploy && cx listen` will give you different results depending on when `cx listen` successfully completes.

Additionally,

* The more useful part is getting confirmation/feedback that the correct thing was deployed to. As far as I can tell there is no easy way to see that is happening.

* You can guess which server is being deployed to by looking at the log messages, but that's not something one wants to have to do, especially since those are internal to c66 and aren't part of the API contract of `listen`.

* Additionally, `listen` contains a great deal of spurious output in the form of `<span> ... </span>` that's clearly meant for consumption by the c66 web interface, so it's tough to read in any kind of reasonable way.

**Comment by khash** [comment]
I agree using the `listen` command is going to cause a race condition, but there is also a `--listen` flag on `redeploy` which you can use. It will start the redeploy and listen at the same time.

We are going to work on publishing more information about the stack and servers it will be deployed to as a result of this and will keep updating this. 

As for the `span` you're right, there is some work still pending on splitting the message streams from the API down depending on who's using them.

**Comment by duncan-bayne** [comment]
Quick question - will the _default_ behaviour still be silent success?

**Comment by kamerblauwlicht** [comment]
yes @duncan-bayne, it's still is. use the --listen switch to get a more verbose output.
