### ISSUE TITLE
cx backups downloads -- better recovery action after failed download

### ISSUE THREAD

**Issue by mindtonic** [cloud66-oss/cx#37]
Hey Guys,

Thanks for all of your amazing tools, they sure make working with Cloud66 a pleasurable experience.

I have a stack that has a very large database. Currently the segmented files go from aa to cc. Occasionally I need to download the backup. Manually downloading each file and then `cat`ting them all together is a tedious process. For this, the `cx backups download` tool is immensely helpful. Unfortunately, because of the size of the database, it frequently fails with a tcp read error:

`error: read tcp 192.168.0.8:49991->54.231.33.25:443: read: connection reset by peer`

It would be really awesome if the tool did two things...

First, because it is putting everything in a standardized directory of its own creation `~/cx_backups/tmp/{id}`, it would be super helpful if it was aware of files that already existed. This would mean that whenever you attempt to restart a backup, it would not start from the beginning, but rather would be able to realize where it left off. This way, even if my following idea does not work, it would serve as a sort of forceful restart to get the job done.

Second would be some sort of error recovery to protect against these failures. In the event that a download is interrupted, it could rescue the error and try to pick up where it left off, with some sort of x attempts safety measure of course.

These improvements would great aid those of us who are attempting to use this script to download very large database backups. If there is anything I can do to help with the specs for this feature request, I would be more than happy to.

Thanks so much!!
Jay Sanders

**Comment by khash** [comment]
Hi Jay,

You are right. We are working on improving the backup downloads soon. Will keep you posted.
