### ISSUE TITLE
cx login: The requested resource could not be found.

### ISSUE THREAD

**Issue by VanyaNeytrino** [cloud66-oss/cx#66]
I'm having the following problem: when I try to execute the "cx login" or "cx info" commands I get the requested resource could not be found error. I can not log in to another account and can not log on to the server, because cx knocks in a non-existent account

**Comment by khash** [comment]
Hi @VanyaNeytrino 

CX supports `--account` flag to allow it being used with multiple accounts. If you need to use CX against different accounts, simply use the `--account` flag with an arbitrary name for the account and run a `stacks list` command which will trigger the authentication process (remember to login to the right account on the web side). 

Once the new account is authenticated, you can use the `--account` with the `login` or `info` commands.

**Comment by VanyaNeytrino** [comment]
Yes, everything is as you say. But when I go to a new account and enter a token from the browser and the utility writes that the token is cached in /Users/ivanrubyst/.cloud66/cx_my_target_acc@gmail.com.json. Next, I enter the CX stacks list command
2018/10/21 16:27: 42 error: the requested resource could not be found. Very strange behavior. What am I doing wrong?

**Comment by khash** [comment]
Can you share the full command you use the second time (the one that fails) please?
